CREATE TABLE `CODE_VALUE` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL,
	`CREATION_DATETIME` DATETIME NOT NULL,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`CODE_SET_ID` VARCHAR(255) NOT NULL,
	`CODE` VARCHAR(255) NOT NULL,
	`STATUS` VARCHAR(255) NOT NULL,
	`NAME` VARCHAR(255),
	`DESCRIPTION` TEXT(65535),
	`DISPLAY_ORDER` INTEGER NOT NULL,
	`MAINTAINABLE` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `USER` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL,
	`CREATION_DATETIME` DATETIME NOT NULL,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`USERNAME` VARCHAR(255) NOT NULL,
	`PASSWORD` TEXT(65535) NOT NULL,
	`ROLE_ID` INTEGER NOT NULL,
	`USER_STATUS_ID` INTEGER NOT NULL,
	`LAST_LOGIN_DATETIME` DATETIME,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `APPOINTMENT` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL,
	`CREATION_DATETIME` DATETIME NOT NULL,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`CUSTOMER_ID` INTEGER NOT NULL,
	`DOCTOR_ID` INTEGER,
	`APPOINTMENT_START_DATETIME` DATETIME,
	`APPOINTMENT_END_DATETIME` DATETIME,
	`APPOINTMENT_STATUS_ID` VARCHAR(255) NOT NULL,
	`CHARGE` DECIMAL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `FEEDBACK` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL,
	`CREATION_DATETIME` DATETIME NOT NULL,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`APPOINTMENT_ID` INTEGER NOT NULL,
	`CONTEXT` TEXT(65535),
	`FEEDBACK_STATUS_ID` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `PAYMENT` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL,
	`CREATION_DATETIME` DATETIME NOT NULL,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`APPOINTMENT_ID` INTEGER NOT NULL,
	`PAYMENT_METHOD_ID` INTEGER NOT NULL,
	`PAYMENT_DATETIME` DATETIME NOT NULL,
	`PAYMENT_STATUS_ID` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `COMMENT` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL,
	`CREATION_DATETIME` DATETIME NOT NULL,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`CUSTOMER_ID` INTEGER NOT NULL,
	`TARGET_USER_ID` INTEGER NOT NULL,
	`RATING` INTEGER NOT NULL,
	`CONTENT` TEXT(65535),
	`COMMENT_STATUS_ID` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `CODE_SET` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL,
	`CREATION_DATETIME` DATETIME NOT NULL,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`CODE` VARCHAR(255) NOT NULL,
	`STATUS` VARCHAR(255) NOT NULL,
	`NAME` VARCHAR(255),
	`DESCRIPTION` TEXT(65535),
	`MAINTAINABLE` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `MEDICINE` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL,
	`CREATION_DATETIME` DATETIME NOT NULL,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`NAME` VARCHAR(255),
	`DESCRIPTION` TEXT(65535),
	`PRICE` DECIMAL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `APPOINTMENT_MEDICINE` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL,
	`CREATION_DATETIME` DATETIME NOT NULL,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`APPOINTMENT_ID` INTEGER NOT NULL,
	`MEDICINE_ID` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `STAFF_DETAIL` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL,
	`CREATION_DATETIME` DATETIME NOT NULL,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPADTE_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`USER_ID` INTEGER NOT NULL,
	`EMAIL` VARCHAR(255),
	`NAME` VARCHAR(255),
	`DATE_OF_BIRTH` DATE,
	`PHONE_NUMBER` VARCHAR(255),
	`PROFILE_PICTURE` TEXT(65535),
	PRIMARY KEY(`ID`)
);


CREATE TABLE `CUSTOMER_DETAIL` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL,
	`CREATION_DATETIME` DATETIME NOT NULL,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`USER_ID` INTEGER NOT NULL,
	`EMAIL` VARCHAR(255),
	`NAME` VARCHAR(255),
	`DATE_OF_BIRTH` DATE,
	`PHONE_NUMBER` VARCHAR(255),
	`PROFILE_PICTURE` TEXT(65535),
	`ALLERGIC` TEXT(65535),
	`BLOOD_TYPE` VARCHAR(255),
	PRIMARY KEY(`ID`)
);


ALTER TABLE `APPOINTMENT`
ADD FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `USER`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `APPOINTMENT`
ADD FOREIGN KEY(`DOCTOR_ID`) REFERENCES `USER`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PAYMENT`
ADD FOREIGN KEY(`APPOINTMENT_ID`) REFERENCES `APPOINTMENT`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `FEEDBACK`
ADD FOREIGN KEY(`APPOINTMENT_ID`) REFERENCES `APPOINTMENT`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `COMMENT`
ADD FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `USER`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `COMMENT`
ADD FOREIGN KEY(`TARGET_USER_ID`) REFERENCES `USER`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CODE_VALUE`
ADD FOREIGN KEY(`CODE_SET_ID`) REFERENCES `CODE_SET`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PAYMENT`
ADD FOREIGN KEY(`PAYMENT_METHOD_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `USER`
ADD FOREIGN KEY(`ROLE_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `COMMENT`
ADD FOREIGN KEY(`COMMENT_STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `APPOINTMENT`
ADD FOREIGN KEY(`APPOINTMENT_STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `FEEDBACK`
ADD FOREIGN KEY(`FEEDBACK_STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PAYMENT`
ADD FOREIGN KEY(`PAYMENT_STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `USER`
ADD FOREIGN KEY(`USER_STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `APPOINTMENT_MEDICINE`
ADD FOREIGN KEY(`APPOINTMENT_ID`) REFERENCES `APPOINTMENT`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `APPOINTMENT_MEDICINE`
ADD FOREIGN KEY(`MEDICINE_ID`) REFERENCES `MEDICINE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `STAFF_DETAIL`
ADD FOREIGN KEY(`USER_ID`) REFERENCES `USER`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CUSTOMER_DETAIL`
ADD FOREIGN KEY(`USER_ID`) REFERENCES `USER`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;