CREATE DATABASE APU_Medical_Centre;
USE APU_Medical_Centre;

CREATE TABLE `CUSTOMER` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL DEFAULT 1,
	`CREATION_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`USERNAME` VARCHAR(255) NOT NULL,
	`PASSWORD` TEXT(65535) NOT NULL,
	`LAST_LOGIN_DATETIME` DATETIME,
	`EMAIL` VARCHAR(255),
	`NAME` VARCHAR(255),
	`DATE_OF_BIRTH` DATE,
	`PHONE_NUMBER` VARCHAR(255),
	`PROFILE_PICTURE` TEXT(65535),
	`ALLERGIC` TEXT(65535),
	`BLOOD_TYPE` VARCHAR(255),
	`STATUS_ID` INTEGER,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `MANAGER` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL DEFAULT 1,
	`CREATION_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`USERNAME` VARCHAR(255) NOT NULL,
	`PASSWORD` TEXT(65535) NOT NULL,
	`LAST_LOGIN_DATETIME` DATETIME,
	`EMAIL` VARCHAR(255),
	`NAME` VARCHAR(255),
	`DATE_OF_BIRTH` DATE,
	`PHONE_NUMBER` VARCHAR(255),
	`PROFILE_PICTURE` TEXT(65535),
	`STATUS_ID` INTEGER,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `COUNTER_STAFF` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL DEFAULT 1,
	`CREATION_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`USERNAME` VARCHAR(255) NOT NULL,
	`PASSWORD` TEXT(65535) NOT NULL,
	`LAST_LOGIN_DATETIME` DATETIME,
	`EMAIL` VARCHAR(255),
	`NAME` VARCHAR(255),
	`DATE_OF_BIRTH` DATE,
	`PHONE_NUMBER` VARCHAR(255),
	`PROFILE_PICTURE` TEXT(65535),
	`STATUS_ID` INTEGER,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `DOCTOR` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL DEFAULT 1,
	`CREATION_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`USERNAME` VARCHAR(255) NOT NULL,
	`PASSWORD` TEXT(65535) NOT NULL,
	`LAST_LOGIN_DATETIME` DATETIME,
	`EMAIL` VARCHAR(255),
	`NAME` VARCHAR(255),
	`DATE_OF_BIRTH` DATE,
	`PHONE_NUMBER` VARCHAR(255),
	`PROFILE_PICTURE` TEXT(65535),
	`STATUS_ID` INTEGER,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `CODE_VALUE` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL DEFAULT 1,
	`CREATION_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`CODE_SET_ID` INTEGER NOT NULL,
	`CODE` VARCHAR(255) NOT NULL,
	`STATUS` VARCHAR(255) NOT NULL,
	`NAME` VARCHAR(255),
	`DESCRIPTION` TEXT(65535),
	`DISPLAY_ORDER` INTEGER NOT NULL,
	`MAINTAINABLE` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `APPOINTMENT` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL DEFAULT 1,
	`CREATION_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`CUSTOMER_ID` INTEGER NOT NULL,
	`DOCTOR_ID` INTEGER,
	`APPOINTMENT_START_DATETIME` DATETIME,
	`APPOINTMENT_END_DATETIME` DATETIME,
	`STATUS_ID` INTEGER NOT NULL,
	`CHARGE` DECIMAL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `FEEDBACK` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL DEFAULT 1,
	`CREATION_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`APPOINTMENT_ID` INTEGER NOT NULL,
	`CONTEXT` TEXT(65535),
	`STATUS_ID` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `PAYMENT` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL DEFAULT 1,
	`CREATION_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`APPOINTMENT_ID` INTEGER NOT NULL,
	`PAYMENT_METHOD_ID` INTEGER NOT NULL,
	`PAYMENT_DATETIME` DATETIME NOT NULL,
	`STATUS_ID` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `COMMENT` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL DEFAULT 1,
	`CREATION_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`CUSTOMER_ID` INTEGER NOT NULL,
	`MANAGER_ID` INTEGER,
	`COUNTER_STAFF_ID` INTEGER,
	`DOCTOR_ID` INTEGER,
	`RATING` INTEGER NOT NULL,
	`CONTENT` TEXT(65535),
	`STATUS_ID` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `CODE_SET` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL DEFAULT 1,
	`CREATION_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`CODE` VARCHAR(255) NOT NULL,
	`STATUS` VARCHAR(255) NOT NULL,
	`NAME` VARCHAR(255),
	`DESCRIPTION` TEXT(65535),
	`MAINTAINABLE` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `MEDICINE` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL DEFAULT 1,
	`CREATION_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`NAME` VARCHAR(255),
	`DESCRIPTION` TEXT(65535),
	`PRICE` DECIMAL,
	PRIMARY KEY(`ID`)
);


CREATE TABLE `APPOINTMENT_MEDICINE` (
	`ID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`VERSION_TIME` INTEGER NOT NULL DEFAULT 1,
	`CREATION_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`CREATE_BY` VARCHAR(255) NOT NULL,
	`LAST_UPDATE_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LAST_UPDATE_BY` VARCHAR(255) NOT NULL,
	`APPOINTMENT_ID` INTEGER NOT NULL,
	`MEDICINE_ID` INTEGER NOT NULL,
	PRIMARY KEY(`ID`)
);

ALTER TABLE `PAYMENT`
ADD FOREIGN KEY(`APPOINTMENT_ID`) REFERENCES `APPOINTMENT`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `FEEDBACK`
ADD FOREIGN KEY(`APPOINTMENT_ID`) REFERENCES `APPOINTMENT`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CODE_VALUE`
ADD FOREIGN KEY(`CODE_SET_ID`) REFERENCES `CODE_SET`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PAYMENT`
ADD FOREIGN KEY(`PAYMENT_METHOD_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `COMMENT`
ADD FOREIGN KEY(`STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `APPOINTMENT`
ADD FOREIGN KEY(`STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `FEEDBACK`
ADD FOREIGN KEY(`STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PAYMENT`
ADD FOREIGN KEY(`STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `APPOINTMENT_MEDICINE`
ADD FOREIGN KEY(`APPOINTMENT_ID`) REFERENCES `APPOINTMENT`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `APPOINTMENT_MEDICINE`
ADD FOREIGN KEY(`MEDICINE_ID`) REFERENCES `MEDICINE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `APPOINTMENT`
ADD FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `APPOINTMENT`
ADD FOREIGN KEY(`DOCTOR_ID`) REFERENCES `DOCTOR`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `DOCTOR`
ADD FOREIGN KEY(`STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CUSTOMER`
ADD FOREIGN KEY(`STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `COUNTER_STAFF`
ADD FOREIGN KEY(`STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `MANAGER`
ADD FOREIGN KEY(`STATUS_ID`) REFERENCES `CODE_VALUE`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `COMMENT`
ADD FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `COMMENT`
ADD FOREIGN KEY(`MANAGER_ID`) REFERENCES `MANAGER`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `COMMENT`
ADD FOREIGN KEY(`COUNTER_STAFF_ID`) REFERENCES `COUNTER_STAFF`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `COMMENT`
ADD FOREIGN KEY(`DOCTOR_ID`) REFERENCES `DOCTOR`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- CODE SET & CODE VALUE
-- CUSTOMER STATUS
INSERT INTO CODE_SET (VERSION_TIME, CREATION_DATETIME, CREATE_BY, LAST_UPDATE_DATETIME, LAST_UPDATE_BY, CODE, STATUS, MAINTAINABLE) VALUES (1, NOW(), "SYS", NOW(), "SYS", "CUSTOMER_STATUS", "ACTIVE", "N");
INSERT INTO CODE_VALUE (VERSION_TIME, CREATION_DATETIME, CREATE_BY, LAST_UPDATE_DATETIME, LAST_UPDATE_BY, CODE, STATUS, MAINTAINABLE, CODE_SET_ID, DISPLAY_ORDER) VALUES (1, NOW(), "SYS", NOW(), "SYS", "ACTIVE", "ACTIVE", "N", (SELECT ID FROM CODE_SET WHERE CODE = "CUSTOMER_STATUS" AND STATUS = "ACTIVE"), 1);
INSERT INTO CODE_VALUE (VERSION_TIME, CREATION_DATETIME, CREATE_BY, LAST_UPDATE_DATETIME, LAST_UPDATE_BY, CODE, STATUS, MAINTAINABLE, CODE_SET_ID, DISPLAY_ORDER) VALUES (1, NOW(), "SYS", NOW(), "SYS", "DELETE", "ACTIVE", "N", (SELECT ID FROM CODE_SET WHERE CODE = "CUSTOMER_STATUS" AND STATUS = "ACTIVE"), 1);
-- MANAGER STATUS
INSERT INTO CODE_SET (VERSION_TIME, CREATION_DATETIME, CREATE_BY, LAST_UPDATE_DATETIME, LAST_UPDATE_BY, CODE, STATUS, MAINTAINABLE) VALUES (1, NOW(), "SYS", NOW(), "SYS", "MANAGER_STATUS", "ACTIVE", "N");
INSERT INTO CODE_VALUE (VERSION_TIME, CREATION_DATETIME, CREATE_BY, LAST_UPDATE_DATETIME, LAST_UPDATE_BY, CODE, STATUS, MAINTAINABLE, CODE_SET_ID, DISPLAY_ORDER) VALUES (1, NOW(), "SYS", NOW(), "SYS", "ACTIVE", "ACTIVE", "N", (SELECT ID FROM CODE_SET WHERE CODE = "MANAGER_STATUS" AND STATUS = "ACTIVE"), 1);
INSERT INTO CODE_VALUE (VERSION_TIME, CREATION_DATETIME, CREATE_BY, LAST_UPDATE_DATETIME, LAST_UPDATE_BY, CODE, STATUS, MAINTAINABLE, CODE_SET_ID, DISPLAY_ORDER) VALUES (1, NOW(), "SYS", NOW(), "SYS", "DELETE", "ACTIVE", "N", (SELECT ID FROM CODE_SET WHERE CODE = "MANAGER_STATUS" AND STATUS = "ACTIVE"), 1);
-- COUNTER_STAFF STATUS
INSERT INTO CODE_SET (VERSION_TIME, CREATION_DATETIME, CREATE_BY, LAST_UPDATE_DATETIME, LAST_UPDATE_BY, CODE, STATUS, MAINTAINABLE) VALUES (1, NOW(), "SYS", NOW(), "SYS", "COUNTER_STAFF_STATUS", "ACTIVE", "N");
INSERT INTO CODE_VALUE (VERSION_TIME, CREATION_DATETIME, CREATE_BY, LAST_UPDATE_DATETIME, LAST_UPDATE_BY, CODE, STATUS, MAINTAINABLE, CODE_SET_ID, DISPLAY_ORDER) VALUES (1, NOW(), "SYS", NOW(), "SYS", "ACTIVE", "ACTIVE", "N", (SELECT ID FROM CODE_SET WHERE CODE = "COUNTER_STAFF_STATUS" AND STATUS = "ACTIVE"), 1);
INSERT INTO CODE_VALUE (VERSION_TIME, CREATION_DATETIME, CREATE_BY, LAST_UPDATE_DATETIME, LAST_UPDATE_BY, CODE, STATUS, MAINTAINABLE, CODE_SET_ID, DISPLAY_ORDER) VALUES (1, NOW(), "SYS", NOW(), "SYS", "DELETE", "ACTIVE", "N", (SELECT ID FROM CODE_SET WHERE CODE = "COUNTER_STAFF_STATUS" AND STATUS = "ACTIVE"), 1);
-- DOCTOR STATUS
INSERT INTO CODE_SET (VERSION_TIME, CREATION_DATETIME, CREATE_BY, LAST_UPDATE_DATETIME, LAST_UPDATE_BY, CODE, STATUS, MAINTAINABLE) VALUES (1, NOW(), "SYS", NOW(), "SYS", "DOCTOR_STATUS", "ACTIVE", "N");
INSERT INTO CODE_VALUE (VERSION_TIME, CREATION_DATETIME, CREATE_BY, LAST_UPDATE_DATETIME, LAST_UPDATE_BY, CODE, STATUS, MAINTAINABLE, CODE_SET_ID, DISPLAY_ORDER) VALUES (1, NOW(), "SYS", NOW(), "SYS", "ACTIVE", "ACTIVE", "N", (SELECT ID FROM CODE_SET WHERE CODE = "DOCTOR_STATUS" AND STATUS = "ACTIVE"), 1);
INSERT INTO CODE_VALUE (VERSION_TIME, CREATION_DATETIME, CREATE_BY, LAST_UPDATE_DATETIME, LAST_UPDATE_BY, CODE, STATUS, MAINTAINABLE, CODE_SET_ID, DISPLAY_ORDER) VALUES (1, NOW(), "SYS", NOW(), "SYS", "DELETE", "ACTIVE", "N", (SELECT ID FROM CODE_SET WHERE CODE = "DOCTOR_STATUS" AND STATUS = "ACTIVE"), 1);

-- DUMMY DATA
INSERT INTO MANAGER (CREATE_BY, LAST_UPDATE_BY, USERNAME, PASSWORD, STATUS_ID) VALUES ("SYS", "SYS", "manager", "password", 
(SELECT ID FROM CODE_VALUE WHERE CODE = "ACTIVE" AND STATUS = "ACTIVE" AND CODE_SET_ID = (SELECT ID FROM CODE_SET WHERE CODE = "MANAGER_STATUS" AND STATUS = "ACTIVE" LIMIT 1) LIMIT 1));

INSERT INTO COUNTER_STAFF ( CREATE_BY,LAST_UPDATE_BY, USERNAME, PASSWORD, STATUS_ID) VALUES ("SYS", "SYS", "staff", "password", 
(SELECT ID FROM CODE_VALUE WHERE CODE = "ACTIVE" AND STATUS = "ACTIVE" AND CODE_SET_ID = (SELECT ID FROM CODE_SET WHERE CODE = "COUNTER_STAFF_STATUS" AND STATUS = "ACTIVE" LIMIT 1) LIMIT 1));

INSERT INTO DOCTOR (CREATE_BY, LAST_UPDATE_BY, USERNAME, PASSWORD, STATUS_ID) VALUES ("SYS", "SYS", "doctor", "password", 
(SELECT ID FROM CODE_VALUE WHERE CODE = "ACTIVE" AND STATUS = "ACTIVE" AND CODE_SET_ID = (SELECT ID FROM CODE_SET WHERE CODE = "DOCTOR_STATUS" AND STATUS = "ACTIVE" LIMIT 1) LIMIT 1));

INSERT INTO CUSTOMER (CREATE_BY,LAST_UPDATE_BY, USERNAME, PASSWORD, STATUS_ID) VALUES ("SYS", "SYS", "customer", "password", 
(SELECT ID FROM CODE_VALUE WHERE CODE = "ACTIVE" AND STATUS = "ACTIVE" AND CODE_SET_ID = (SELECT ID FROM CODE_SET WHERE CODE = "CUSTOMER_STATUS" AND STATUS = "ACTIVE" LIMIT 1) LIMIT 1));